---
title: "Starwars"
author: "Pierson Cooke"
date: "2023-02-23"
output: html_document
---


```{r}

library(RJSONIO)
library(tidyverse)

starwarsFunction <- function(file_path) {
  
  data <- RJSONIO::fromJSON(file_path)

  nodes <- 
    data[1] %>% 
    unlist() %>% 
    unlist() %>% 
    matrix(ncol = 3, byrow = T) %>% 
    as_data_frame() %>% 
    rename(MovieChar = V1, 
           Scenes = V2,
           Color = V3) %>%
    mutate(UniqueID = row_number() - 1,
           MovieChar = tolower(MovieChar)) %>% 
    relocate(UniqueID, everything())

  link <-
    data[2] %>% 
    unlist() %>% 
    unlist() %>% 
    matrix(ncol = 3, byrow = T) %>% 
    as_data_frame() %>% 
    rename(Source = V1, 
           Targtet = V2,
           Value = V3)
  
  return(list(nodes = nodes, link = link))

}

```

```{r}

all_interactions <- starwarsFunction("/Users/piersoncooke/networksproject/Gephi-Data/starwars-full-interactions.json")

all_interactions_nodes <- all_interactions$nodes
all_interactions_links <- all_interactions$link

all_interactions_nodes <- all_interactions_nodes[,-4]

all_interactions_links$Type <- "Undirected"

write.csv(all_interactions_nodes, "/Users/piersoncooke/Desktop/star-wars-network-data-master/Networks-Project/nodes.csv", 
          row.names = FALSE)

write.csv(all_interactions_links, "/Users/piersoncooke/Desktop/star-wars-network-data-master/Networks-Project/links.csv", 
          row.names = FALSE)
```

